### ISSUE TITLE
Ash about database

### ISSUE THREAD

**Issue by nguyendaovinhhai** [abhishek72850/Fingerprint-Recognition#1]
Can you tell about your database name?

**Comment by abhishek72850** [comment]
u can get it from here [https://www.kaggle.com/ruizgara/socofing?](url)

**Comment by nguyendaovinhhai** [comment]
can i use data db2_b ? and where do i put data in folder ?

**Comment by abhishek72850** [comment]
put your fingerprint images in **fingerprint_dataset** folder, make this folder at root level of this repo

Not sure about **db2_b**, don't know about this

**Comment by nguyendaovinhhai** [comment]
Thank you
